### PR TITLE
Make scrollability works in none-mobile browsers, so we can test it easier

### PR DESCRIPTION
**Pull request by Tin**
Adapted the touch events by mouse click events, so we can simulate touch events in desktop browsers.

### CODE REVIEW

**Comment by doctyper** [comment]
How about this rather than UA sniffing:

```
var isTouch = "ontouchstart" in window;
```

**Comment by joehewitt** [comment]
I used to have this working but I pulled it out since I find it extremely awkward to scroll with a mouse.  I guess the only reason to support desktop scrolling is so we can use superior desktop debugging tools.

**Comment by joehewitt** [comment]
Doctyper's suggestion is definitely better than the UA sniffing, and is what I was using before I pulled out desktop support.  Tin, could you make that change and also remove the easeOutExpo changes?  You can submit that as a separate pull request, since it's not quite related.

**Comment by Tin** [comment]
Yes, Doctyper's suggestion is definitely right. I pushed this changes. I'm new on using pull request, I should not using master branch for pull this pull request. I will close this one, and send another.

**Pull request closed without merging**
