### PR TITLE
Make scrollability works in none-mobile browsers, so we can debug it easier

### PR DESCRIPTION
**Pull request by Tin**
Adapted the touch events by mouse click events, so we can simulate touch events in desktop browsers. Support desktop scrolling so we can use superior desktop debugging tools (Joe added this comment).

### CODE REVIEW

**Comment by mgcrea** [comment]
Need this badly, please !

**Comment by zanona** [comment]
+1

**Comment by ghost** [comment]
Sounds a good idea, but is this good ? I tried to do it, but it looks weird on desktop browsers.
I had to use event.preventDefault() with onTouchStart for example otherwise I was starting a text selection instead.
Without talking about desktop, there is also an issue like the #20 about how to manage event handlers.

The library was designed for mobile web, it's good for me.
My question is more like " I am using scrollability in mobile web browsers, and I would like to bring an alternative user experience to desktop browsers too".

Is anybody thinking the same ?

**Comment by zanona** [comment]
yes definitely :)

**Comment by Tin** [comment]
@getphuture I don't think we should use scrollability.js in browser. But we need to do the development in desktop browser, if we can test our own event handlers working with scrollability.js, it will boost the development process.

Our mobile web development is mostly finished in desktop browsers.

**Comment by joehewitt** [comment]
Fixed.

**Pull request closed without merging**
